# Generated by Django 5.1.1 on 2024-10-06 11:20

import django.db.models.deletion
import thumbs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=thumbs.models.product_image_path, verbose_name='Upload Image')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='houses.house')),
            ],
        ),
    ]
