# Generated by Django 5.1.1 on 2024-10-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_agent'),
        ('thumbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house'),
        ),
    ]
